artifacts_root: artifacts
# my dataset link : "https://drive.google.com/file/d/1NY__w7jcreT_kem8etYXak-5h8pCEzYK/view?usp=sharing"
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
